development:
  adapter: postgresql
  encoding: unicode
  database: lawa_develoment
  pool: 5
  username: Chris

test:
  adapter: postgresql
  encoding: unicode
  database: lawa_development
  pool: 5
  username: Chris
